language: java
branches:
  only:
  - master
os:
  - linux
matrix:
  include:
    # Headless Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
      - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
after_success:
- ./gradlew jacocoTestReport coveralls
# A peculiarity of dependency caching in Gradle means that to avoid uploading the cache after every
# build you need to add the following lines to your .travis.yml:
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
